"""Transparent expert matching with explicit evidence and constraints."""

from peermatchlab.affinity import Affinity, AffinityScorer, load_affinities_csv
from peermatchlab.assignment import AssignmentEngine, AssignmentStrategy
from peermatchlab.embedding import (
    EmbeddingProvider,
    EmbeddingRequest,
    EmbeddingScore,
    FrozenJsonlEmbeddingProvider,
    embedding_requests,
    request_sha256,
    score_embedding_expertise,
    write_embedding_run,
)
from peermatchlab.expertise import (
    EvidenceDocument,
    ExpertiseAggregation,
    ExpertiseConfig,
    ExpertiseCorpus,
    ExpertiseModel,
    ExpertiseModelName,
    ExpertiseRun,
    ExpertiseScore,
    TermContribution,
    build_expertise_corpus,
    generate_expertise,
)
from peermatchlab.expertise_io import (
    ExpertiseConfigSource,
    LocalExpertiseInputs,
    load_expertise_config_source,
    load_local_domain_expertise_inputs,
    load_openreview_expertise_snapshot,
    local_domain_inputs,
    write_expertise_run,
)
from peermatchlab.keyphrases import (
    Keyphrase,
    KeyphraseConfig,
    KeyphraseRecord,
    extract_keyphrases,
    rank_keyphrases,
    read_keyphrase_source,
    write_keyphrase_run,
)
from peermatchlab.models import (
    Assignment,
    AssignmentDiagnostics,
    DemandDiagnostic,
    Document,
    Expert,
    FeasibilityStatus,
    MatchPlan,
    Publication,
    UnmetReason,
)
from peermatchlab.openreview import (
    load_openreview_submissions,
    load_reviewer_ids,
    openreview_submissions_from_records,
    reviewer_ids_to_experts,
)
from peermatchlab.openreview_api import (
    ExpertiseFetchPolicy,
    OpenReviewClient,
    OpenReviewClientConfig,
    OpenReviewError,
    OpenReviewExpertiseEvidence,
    OpenReviewHttpError,
    OpenReviewProtocolError,
    OpenReviewSnapshot,
    OpenReviewTransportError,
    RetryPolicy,
    fetch_openreview_snapshot,
    fetch_reviewer_expertise,
    write_openreview_snapshot,
)
from peermatchlab.openreview_publish import (
    AssignmentEdge,
    AssignmentWriteTransport,
    PublishPlan,
    PublishReceipt,
    PublishScope,
    RemoteContext,
    prepare_publish_plan,
    publish_assignment_plan,
    write_publish_artifact,
)
from peermatchlab.scoring import MatchScorer, ScoreWeights
from peermatchlab.what_if import WhatIfPlan, WhatIfScenario, compare_what_if

__all__ = [
    "Affinity",
    "AffinityScorer",
    "Assignment",
    "AssignmentDiagnostics",
    "AssignmentEdge",
    "AssignmentEngine",
    "AssignmentStrategy",
    "AssignmentWriteTransport",
    "DemandDiagnostic",
    "Document",
    "EmbeddingProvider",
    "EmbeddingRequest",
    "EmbeddingScore",
    "EvidenceDocument",
    "Expert",
    "ExpertiseAggregation",
    "ExpertiseConfig",
    "ExpertiseConfigSource",
    "ExpertiseCorpus",
    "ExpertiseFetchPolicy",
    "ExpertiseModel",
    "ExpertiseModelName",
    "ExpertiseRun",
    "ExpertiseScore",
    "FeasibilityStatus",
    "FrozenJsonlEmbeddingProvider",
    "Keyphrase",
    "KeyphraseConfig",
    "KeyphraseRecord",
    "LocalExpertiseInputs",
    "MatchPlan",
    "MatchScorer",
    "OpenReviewClient",
    "OpenReviewClientConfig",
    "OpenReviewError",
    "OpenReviewExpertiseEvidence",
    "OpenReviewHttpError",
    "OpenReviewProtocolError",
    "OpenReviewSnapshot",
    "OpenReviewTransportError",
    "Publication",
    "PublishPlan",
    "PublishReceipt",
    "PublishScope",
    "RemoteContext",
    "RetryPolicy",
    "ScoreWeights",
    "TermContribution",
    "UnmetReason",
    "WhatIfPlan",
    "WhatIfScenario",
    "build_expertise_corpus",
    "compare_what_if",
    "embedding_requests",
    "extract_keyphrases",
    "fetch_openreview_snapshot",
    "fetch_reviewer_expertise",
    "generate_expertise",
    "load_affinities_csv",
    "load_expertise_config_source",
    "load_local_domain_expertise_inputs",
    "load_openreview_expertise_snapshot",
    "load_openreview_submissions",
    "load_reviewer_ids",
    "local_domain_inputs",
    "openreview_submissions_from_records",
    "prepare_publish_plan",
    "publish_assignment_plan",
    "rank_keyphrases",
    "read_keyphrase_source",
    "request_sha256",
    "reviewer_ids_to_experts",
    "score_embedding_expertise",
    "write_embedding_run",
    "write_expertise_run",
    "write_keyphrase_run",
    "write_openreview_snapshot",
    "write_publish_artifact",
]

__version__ = "0.15.0"
